version: '3'

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        command: [ "/bin/bash", "-c", "php artisan serve --port=8000 --host=0.0.0.0" ]

    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    redis:
        container_name: redis
        image: redis:7.0
        ports:
            - "6379:6379"

volumes:
    mysql:
        driver: local
